version: '3.8'

services:
  victim:
    build: ./victim
    ports:
      - "5000:5000"
    networks:
      - csrf_net
  attacker:
    build: ./attacker
    ports:
      - "5001:5001"
    depends_on:
      - victim
    networks:
      - csrf_net

networks:
  csrf_net: