version: '3.8'

services:
  victim:
    build: ./victim
    ports:
      - "5000:5000"
    networks:
      labnet:
        ipv4_address: 172.28.0.20
    dns:
      - 172.28.0.11 # use attacker DNS
    depends_on:
      - attacker
      - admin

  attacker:
    build: ./attacker
    networks:
      labnet:
        ipv4_address: 172.28.0.11
    ports:
      - "8080:80" # attacker visible web service (optional)

  admin:
    build: ./admin
    networks:
      labnet:
        ipv4_address: 172.28.0.5
    expose:
      - "8081"

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
