version: '3.8'

services:
  message_board:
    build: ./message_board
    ports:
      - "6080:5000"
    environment:
      - ATTACKER_BASE_URL=http://attacker.127.0.0.1.nip.io:6001
    networks:
      - csrf_net
  attacker:
    build: ./attacker
    ports:
      - "6001:5001"
    environment:
      - VICTIM_BASE_URL=http://victim.127.0.0.1.sslip.io:6080
    depends_on:
      - message_board
    networks:
      - csrf_net

networks:
  csrf_net: